
# .streamlit/config.toml

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#00F6E5" # A vibrant cyan/teal

# Background color for the main content area.
backgroundColor = "#0F1116"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#1E2027"

# Color used for almost all text.
textColor = "#FAFAFA"

# Font family for all text in the app, except code blocks.
# One of "sans serif", "serif", or "monospace".
font = "sans serif"
